services:
  home-ai-controller:
    build: .
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    network_mode: host
  home-ai-streamlit:
    build: ./chatbot
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: host